import pandas as pd

df = pd.read_csv('site_data_daily.csv')
df

df1 = pd.read_csv('site_to_location.csv')
df1

merged_df = df.merge(df1[['site_id', 'state']], on='site_id', how='left')
merged_df

In [9]:
merged_df['Time'] = merged_df['Time'].replace({'All Day': 'a', 'Night': 'b', 'Morning': 'c', 'Afternoon': 'd', 'Evening': 'e'})
agg_df = merged_df.groupby(['state', 'Date', 'Time']).agg({'PM2.5_min': 'min', 'PM2.5_max': 'max', 'PM2.5_mean': 'mean', 'PM10_min': 'min', 'PM10_max': 'max', 'PM10_mean': 'mean', 'NO_min': 'min', 'NO_max': 'max', 'NO_mean': 'mean', 'NO2_min': 'min',
           'NO2_max': 'max', 'NO2_mean': 'mean', 'NOx_min': 'min', 'NOx_max': 'max', 'NOx_mean': 'mean', 'NH3_min': 'min',
           'NH3_max': 'max', 'NH3_mean': 'mean', 'SO2_min': 'min', 'SO2_max': 'max', 'SO2_mean': 'mean', 'CO_min': 'min',
           'CO_max': 'max', 'CO_mean': 'mean', 'Ozone_min': 'min', 'Ozone_max': 'max', 'Ozone_mean': 'mean', 'AQI_min': 'min',
           'AQI_max': 'max', 'AQI_mean': 'mean'}).reset_index()
agg_df['Time'] = agg_df['Time'].replace({'a': 'All Day', 'b': 'Night', 'c': 'Morning', 'd': 'Afternoon', 'e': 'Evening'})
agg_df

,state,Date,Time,PM2.5_min,PM2.5_max,PM2.5_mean,PM10_min,PM10_max,PM10_mean,NO_min,...,SO2_mean,CO_min,CO_max,CO_mean,Ozone_min,Ozone_max,Ozone_mean,AQI_min,AQI_max,AQI_mean
0,Andhra Pradesh,2016-07-08,All Day,23.50,59.00,40.604167,61.25,143.00,93.031250,10.78,...,6.337917,0.69,1.58,1.092500,3.830000,132.18,16.337083,85.0,147.0,111.958333
1,Andhra Pradesh,2016-07-08,Night,23.50,56.00,41.208333,61.25,126.00,91.458333,10.78,...,5.266667,0.69,0.95,0.781667,6.620000,132.18,30.365000,85.0,147.0,116.000000
2,Andhra Pradesh,2016-07-08,Morning,25.00,47.25,39.916667,68.00,106.25,91.625000,21.82,...,6.975000,0.76,1.16,0.993333,6.250000,15.40,9.578333,90.0,147.0,137.500000
3,Andhra Pradesh,2016-07-08,Afternoon,39.50,59.00,45.625000,94.75,143.00,108.708333,20.15,...,4.921667,1.06,1.58,1.325000,16.733333,21.03,18.688333,92.0,101.0,96.500000
4,Andhra Pradesh,2016-07-08,Evening,28.50,45.00,35.666667,62.00,111.00,80.333333,31.37,...,8.188333,1.12,1.45,1.270000,3.830000,11.17,6.716667,93.0,101.0,97.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258065,West Bengal,2023-03-31,All Day,7.35,293.32,34.622949,24.62,682.54,79.576490,0.61,...,10.682532,0.03,2.26,0.567422,4.730000,107.17,35.820000,40.0,121.0,77.526309
258066,West Bengal,2023-03-31,Night,7.35,92.88,27.898205,24.62,177.06,59.875897,2.00,...,8.302949,0.03,2.26,0.457312,4.730000,107.17,44.490385,54.0,121.0,82.707799
258067,West Bengal,2023-03-31,Morning,7.82,92.88,31.980641,27.27,177.06,69.799615,1.41,...,10.946026,0.10,1.89,0.596691,4.810000,60.70,31.942436,42.0,121.0,77.794872
258068,West Bengal,2023-03-31,Afternoon,12.05,92.88,39.896923,47.26,177.06,85.642564,0.61,...,14.677051,0.14,1.70,0.637865,7.400000,104.83,42.234744,40.0,121.0,74.961538
258069,West Bengal,2023-03-31,Evening,9.66,293.32,38.716026,44.24,682.54,102.987885,1.66,...,8.804103,0.15,1.15,0.577821,4.950000,64.16,24.612436,50.0,121.0,74.641026

In [10]:
agg_df.head(10)

,state,Date,Time,PM2.5_min,PM2.5_max,PM2.5_mean,PM10_min,PM10_max,PM10_mean,NO_min,...,SO2_mean,CO_min,CO_max,CO_mean,Ozone_min,Ozone_max,Ozone_mean,AQI_min,AQI_max,AQI_mean
0,Andhra Pradesh,2016-07-08,All Day,23.50,59.00,40.604167,61.25,143.00,93.031250,10.78,...,6.337917,0.69,1.58,1.092500,3.830000,132.18,16.337083,85.0,147.0,111.958333
1,Andhra Pradesh,2016-07-08,Night,23.50,56.00,41.208333,61.25,126.00,91.458333,10.78,...,5.266667,0.69,0.95,0.781667,6.620000,132.18,30.365000,85.0,147.0,116.000000
2,Andhra Pradesh,2016-07-08,Morning,25.00,47.25,39.916667,68.00,106.25,91.625000,21.82,...,6.975000,0.76,1.16,0.993333,6.250000,15.40,9.578333,90.0,147.0,137.500000
3,Andhra Pradesh,2016-07-08,Afternoon,39.50,59.00,45.625000,94.75,143.00,108.708333,20.15,...,4.921667,1.06,1.58,1.325000,16.733333,21.03,18.688333,92.0,101.0,96.500000
4,Andhra Pradesh,2016-07-08,Evening,28.50,45.00,35.666667,62.00,111.00,80.333333,31.37,...,8.188333,1.12,1.45,1.270000,3.830000,11.17,6.716667,93.0,101.0,97.833333
5,Andhra Pradesh,2016-07-09,All Day,18.00,55.75,33.250000,41.00,120.25,77.645833,5.55,...,8.790000,0.67,1.78,1.004167,5.950000,66.43,18.378333,74.0,90.0,80.583333
6,Andhra Pradesh,2016-07-09,Night,20.25,28.00,24.666667,41.00,64.00,54.541667,5.55,...,9.730000,0.67,0.82,0.710000,6.980000,66.43,22.278333,83.0,90.0,85.666667
7,Andhra Pradesh,2016-07-09,Morning,23.00,38.00,29.708333,52.00,75.75,65.458333,9.28,...,8.025000,0.75,1.02,0.883333,9.050000,20.88,12.948333,76.0,82.0,78.666667
8,Andhra Pradesh,2016-07-09,Afternoon,18.00,55.75,40.208333,83.25,109.50,97.166667,15.10,...,7.213333,0.92,1.29,1.093333,21.950000,33.85,28.861667,74.0,77.0,76.000000
9,Andhra Pradesh,2016-07-09,Evening,29.75,46.00,38.416667,76.75,120.25,93.416667,16.62,...,10.191667,1.01,1.78,1.330000,5.950000,13.05,9.425000,75.0,89.0,82.000000

In [11]:
agg_df.to_csv('state_data_daily.csv', index=False)